/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BikeDialog: typeof import('./src/components/BikeDialog.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    DrawButton: typeof import('./src/components/DrawButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/Header.vue')['default']
    MapControl: typeof import('./src/components/MapControl.vue')['default']
    OlMap: typeof import('./src/components/OlMap.vue')['default']
    OlMap_1: typeof import('./src/components/OlMap_1.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    PopupMenu: typeof import('./src/components/PopupMenu.vue')['default']
    RegionDialog: typeof import('./src/components/RegionDialog.vue')['default']
    RegionTable: typeof import('./src/components/RegionTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
